name: open-cuak-apps
services:
  open-cuak-web:
    image: ghcr.io/aident-ai/open-cuak-web:${OPEN_CUAK_VERSION:-stable}
    container_name: open-cuak-web
    restart: always
    ports:
      - '3000:3000'
    networks:
      - default
      - supabase_supabase-network
    volumes:
      - ../.env.local:/app/apps/web/.env
      - ../.env.production:/app/apps/web/.env.production

  open-cuak-browserless:
    image: ghcr.io/aident-ai/open-cuak-browserless:${OPEN_CUAK_VERSION:-stable}
    container_name: open-cuak-browserless
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '11975:11975'
      - '11976:3000'
      - '50000:50000'
    networks:
      - default
      - supabase_supabase-network
    volumes:
      - ../.env.local:/app/.env
      - ../.env.production:/app/.env.production

networks:
  supabase_supabase-network:
    external: true
